export type FailureKind =
  | 'UnrecognizedError'
  | 'InvalidArgumentsError'
  | 'DuplicateEventError'
  | 'WorkflowFileSaveCollisionError'
  | 'WorkflowFileNotFoundError'
  | 'WorkflowFileCorruptedError'
  | 'WorkflowAlreadyCompletedError'
  | 'WorkflowInvalidStateError'
  | 'BedrockInvokeTransientError'
  | 'BedrockInvokePermanentError'
