export enum EventStoreEventName {
  USER_QUERY_RECEIVED = 'USER_QUERY_RECEIVED',
  QUERY_ENRICHED = 'QUERY_ENRICHED',
  ENRICHED_QUERY_GRADED = 'ENRICHED_QUERY_GRADED',
  QUERY_RESPONDED = 'QUERY_RESPONDED',
}
