export enum EventStoreEventName {
  WORKFLOW_STARTED = 'WORKFLOW_STARTED',
  WORKFLOW_CONTINUED = 'WORKFLOW_CONTINUED',
  WORKFLOW_CREATED = 'WORKFLOW_CREATED',
  WORKFLOW_AGENTS_DEPLOYED = 'WORKFLOW_AGENTS_DEPLOYED',
  WORKFLOW_PROMPT_ENHANCED = 'WORKFLOW_PROMPT_ENHANCED',
  WORKFLOW_PROMPT_COMPLETED = 'WORKFLOW_PROMPT_COMPLETED',
}
