export enum EventStoreEventName {
  JOB_CREATED_EVENT = 'JOB_CREATED_EVENT',
  STEP_PROCESSED_EVENT = 'STEP_PROCESSED_EVENT',
  WORKFLOW_CREATED_EVENT = 'WORKFLOW_CREATED_EVENT',
  WORKFLOW_AGENTS_DEPLOYED_EVENT = 'WORKFLOW_AGENTS_DEPLOYED_EVENT',
  WORKFLOW_PROMPT_ENHANCED_EVENT = 'WORKFLOW_PROMPT_ENHANCED_EVENT',
  WORKFLOW_PROMPT_COMPLETED_EVENT = 'WORKFLOW_PROMPT_COMPLETED_EVENT',
}
