export enum EventStoreEventName {
  WORKFLOW_STARTED_EVENT = 'WORKFLOW_STARTED_EVENT',
  WORKFLOW_CONTINUED_EVENT = 'WORKFLOW_CONTINUED_EVENT',
  WORKFLOW_CREATED_EVENT = 'WORKFLOW_CREATED_EVENT',
  WORKFLOW_AGENTS_DEPLOYED_EVENT = 'WORKFLOW_AGENTS_DEPLOYED_EVENT',
  WORKFLOW_PROMPT_ENHANCED_EVENT = 'WORKFLOW_PROMPT_ENHANCED_EVENT',
  WORKFLOW_PROMPT_COMPLETED_EVENT = 'WORKFLOW_PROMPT_COMPLETED_EVENT',
}
