export enum EventStoreEventName {
  JOB_CREATED_EVENT = 'JOB_CREATED_EVENT',
  STEP_PROCESSED_EVENT = 'STEP_PROCESSED_EVENT',
  WORKFLOW_CREATED_EVENT = 'WORKFLOW_CREATED_EVENT',
  WORKFLOW_ASSISTANTS_DEPLOYED_EVENT = 'WORKFLOW_ASSISTANTS_DEPLOYED_EVENT',
  WORKFLOW_STEP_PROCESSED_EVENT = 'WORKFLOW_STEP_PROCESSED_EVENT',
  WORKFLOW_COMPLETED_EVENT = 'WORKFLOW_COMPLETED_EVENT',
}
