@baseUrl = {{$dotenv WORKFLOW_SERVICE_API_BASE_URL}}

### Send the initial query and name the SendQueryApi
### By adding @name, we can reference this request's response later.
### POST
# @name sendQuery
POST {{baseUrl}}/api/v1/workflow-service/sendQuery
Origin: https://localhost
Content-Type: application/json

{
  "query": "I am writing a TypeScript with Next.js application. I need to implement a feature that allows users to upload images and display them in a gallery. Can you help me with that? Please provide step by step instructions and commands to execute."
}


### Get the workflow ID from the response
@workflowId = {{sendQuery.response.body.workflowId}}


### Inject the workflow ID into the GetLatestWorkflowApi request
### POST
POST {{baseUrl}}/api/v1/workflow-service/getLatestWorkflow
Origin: https://localhost
Content-Type: application/json

{
  "workflowId": "{{workflowId}}"
}

### Passing a hardcoded workflow ID for testing purposes
### POST
POST {{baseUrl}}/api/v1/workflow-service/getLatestWorkflow
Origin: https://localhost
Content-Type: application/json

{
  "workflowId": "workflow-2025-08-12T02-14-45-525Z-I-am-planning-a-trip-31ARRt1jInIFIDM6pFHrkLcrsCk"
}


### CORS QUERY
### OPTIONS ###
OPTIONS {{baseUrl}}/api/v1/workflow-service/getLatestWorkflow
Origin: https://localhost
Access-Control-Request-Method: POST
