@baseUrl = {{$dotenv WORKFLOW_SERVICE_API_BASE_URL}}

### WORKFLOW_CREATED_EVENT
### POST ###
POST {{baseUrl}}/api/v1/workflow-service/sendQuery
Origin: https://localhost
Content-Type: application/json

{
  "query": "Who build the pyramids?",
  "enhancePromptRounds": 2,
  "enhanceResultRounds": 1
}

### WORKFLOW_CREATED_EVENT
### POST ###
POST {{baseUrl}}/api/v1/workflow-service/sendQuery
Origin: https://localhost
Content-Type: application/json

{
  "query": "How can I solve a quadratic equation?",
  "enhancePromptRounds": 3,
  "enhanceResultRounds": 2
}

### WORKFLOW_CREATED_EVENT
### POST ###
POST {{baseUrl}}/api/v1/workflow-service/sendQuery
Origin: https://localhost
Content-Type: application/json

{
  "query": "Can you design a business plan for an ice cream shop? The idea is to grow to 20 stores in 5 years.",
  "enhancePromptRounds": 5,
  "enhanceResultRounds": 4
}

### WORKFLOW_CREATED_EVENT
### POST ###
POST {{baseUrl}}/api/v1/workflow-service/sendQuery
Origin: https://localhost
Content-Type: application/json

{
  "query": "I am writing a TypeScript with Next.js application. I need to implement a feature that allows users to upload images and display them in a gallery. Can you help me with that?",
  "enhancePromptRounds": 1,
  "enhanceResultRounds": 1
}

### CORS QUERY
### OPTIONS ###
OPTIONS {{baseUrl}}/api/v1/workflow-service/sendQuery
Origin: https://localhost
Access-Control-Request-Method: POST
